### ISSUE TITLE
Fix events taking absurdly long to reload

### ISSUE THREAD

**Issue by NatVIII** [NatVIII/rva.rip#24]
**Describe the bug**
As of now, when an event updates on one of the calendars that rva.rip pulls from it won't load for an absurdly long time. I think it might be four hours if I understand @bytewife's code correctly.

**Expected behavior**
Let's make it so that the calendar rechecks all it's sources atleast, say, every fifteen minutes? We'll wipe the cache if it's more than fifteen.

**Comment by bytewife** [comment]
This is intended because of rate limits and/or server costs. It's been a bit, but the server costs may not be an issue any more. The rate limit depends on the API, but the Instagram one is particularly egregious for non-formally-approved uses (I never bothered to figure this out). I'm short on time at the moment- would love help investigating!

**Comment by NatVIII** [comment]
That'd be so awesome Ivy, I've also been super busy lately but if you'd like to contribute you got my number!

**Comment by NatVIII** [comment]
For future reference too, I found that Vercel just didn't update the page at all for nearly a week; that's crazy! I'm gonna try and trawl through the old commits and see if I can find one that's still online that actually updated, since it seems like it updates in a dev environment but not in Vercel

**Comment by NatVIII** [comment]
Fortunately I've fixed this with commit 50226c8…. I don't know how the hell that fixed it, but it did, and I'd love to research why the hell it works at some point but I don't think I'll be so lucky soon.

**Comment by NatVIII** [comment]
Yeah it turns out that was just because the cache for Vue projects wipes every 31 days, so I just saw a page that had to re-grab everything. Woops. Looks like I might not really have a way to just search for this issue easily by trawling through old working code without opening *every single link* ;-;

**Comment by NatVIII** [comment]
May have just adjusted this with pull #72. Come back in a day and make sure and then cross this off if it did!
